apiVersion: apps/v1
kind: Deployment
metadata:
  name: andrewdomain-blog-deployment
  labels:
    app: andrewdomain-blog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: andrewdomain-blog
  template:
    metadata:
      labels:
        app: andrewdomain-blog
    spec:
      containers:
      - name: andrewdomain-blog
        image: x7uplime/andrewdomain-blog:v1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: andrewdomain-blog-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: andrewdomain-blog
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: andrewdomain-blog
  sessionAffinity: None
